### ISSUE TITLE
LOOT wont detect SSE

### ISSUE THREAD

**Issue by Wolfstorm321** [loot/loot#1152]
Until a week ago, I had to put LOOT inside SSE folder to be able to detect it. 
Today this is no longer possible. 
Sad. 

[09:20:20.762611] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[09:20:21.870611] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (02009d55e91f7c03f8e36b45cc9ebdfe075a85dc): libgit2 error
[09:20:21.871611] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5757: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5757:9194)
[09:20:45.396411] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5757: TypeError: Cannot set property 'generalMessages' of undefined
    at e.then.then.e (http://loot/ui/app.bundle.js:5757:22007)
[09:20:51.138611] [error]: Exception while executing query: Git operation failed. Details: -3; object not found - no match for id (43009d55e91f7c03f8e36b45cc9ebdfe075a85dc): libgit2 error
[09:20:51.139611] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5757: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5757:9194)

**Comment by Ortham** [comment]
I've seen a few of these errors recently, I'm not sure why they're happening all of a sudden...

You can work around it by deleting your `%LOCALAPPDATA%\LOOT\SkyrimSE\.git` folder (it may be hidden) and letting LOOT recreate it.

**Comment by Wolfstorm321** [comment]
I deleted the folder, reinstalled LOOT, this time outside of Skyrim folder. I installed in Program Files (x86). 

And it detected Skyrim, without any issue.

**Comment by CptMcSplody** [comment]
> I deleted the folder, reinstalled LOOT, this time outside of Skyrim folder. I installed in Program Files (x86).
> And it detected Skyrim, without any issue.

Closing as it seems to be resolved and it's similar to another active issue #1158
