### ISSUE TITLE
LOOT works flawlessly with Fallout 4 through MO, but refuses to detect SSE

### ISSUE THREAD

**Issue by Barerock** [loot/loot#1168]
I've already posted on the SSE Nexus page if I leave any details out here.
As the title states, even a fresh install of the 0.14.6 LOOT refuses to sort or update master lists with Skyrim Special Edition. I've fresh installed at least a dozen times now and started up the SSE launcher through steam and MO alike each time. The application fails to ask me about games, but auto detects both Fallout 4 (F4) and Skyrim (SSE). 

Trying to sort with LOOT provides this message: **"Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information."**

Attempting to change the settings and clicking 'APPLY' provides this message: **"Cannot read property 'folder' of undefined"**

The debug log shows this: **"[16:05:17.816694] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[16:05:18.968563] [error]: Failed to evaluate condition "file("F4SE/Plugins/place.dll") and file("../f4se_loader.exe") and ((version("F4SE/Plugins/place.dll", "1.18.0.1130", ==) and version("../Fallout4.exe", "1.10.130.0", !=)) or (version("F4SE/Plugins/place.dll", "1.18.0.1130", <) and version("../Fallout4.exe", "1.10.130.0", ==)))". Details: An error was encountered while accessing the path "C:\steam\steamapps\common\Fallout 4\Data\F4SE/Plugins/place.dll": The volume for a file has been externally altered so that the opened file is no longer valid. (os error 1006)
[16:05:18.968994] [error]: Exception while executing query: Failed to evaluate condition "file("F4SE/Plugins/place.dll") and file("../f4se_loader.exe") and ((version("F4SE/Plugins/place.dll", "1.18.0.1130", ==) and version("../Fallout4.exe", "1.10.130.0", !=)) or (version("F4SE/Plugins/place.dll", "1.18.0.1130", <) and version("../Fallout4.exe", "1.10.130.0", ==)))". Details: An error was encountered while accessing the path "C:\steam\steamapps\common\Fallout 4\Data\F4SE/Plugins/place.dll": The volume for a file has been externally altered so that the opened file is no longer valid. (os error 1006)
[16:05:18.970023] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5757: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5757:9194)
[16:06:02.729033] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5757: TypeError: Cannot read property 'folder' of undefined
    at Cl.then.catch.then (http://loot/ui/app.bundle.js:5757:26689)"**

I've checked the filepaths and the keywords applied in the MO application directory and found that they are identical. I'm only using one install of the program, so all files are shared. Running the program through my F4 profile works flawlessly and provides all details with zero program errors. 

I'm not sure how to fix this any other way. I've looked through pretty much every relevant forum post going back 3 years.

**Comment by Ortham** [comment]
Those `os error 1006` errors look like they might be related to MO's filesystem stuff, I'm not sure why it causes issues for some people or what you can do about it.

I think I see why the `Cannot read property 'folder' of undefined` error is happening though, I can fix that.

**Comment by Barerock** [comment]
Is the fix for the latter issue on your side or mine? I'm confused by the issue because LOOT worked fine for ages and now it's doing this for only one profile.

**Comment by Ortham** [comment]
On my side - try this build: https://bintray.com/loot/snapshots/download_file?file_path=loot_0.14.6-9-g2f8efbb_fix-undefined-game-error.7z

**Comment by Barerock** [comment]
That did the trick. Working optimally now! Thanks for the time!

**Comment by Ortham** [comment]
OK, closing this as the fix is merged as of a20ada94eeb8f844128addbc06b527d3c712c2eb.
