### ISSUE TITLE
Could not fetch masterlist

### ISSUE THREAD

**Issue by TheButlah** [loot/loot#1542]
I was unable to fetch the masterlist. I am running on the latest released LOOT. This also failed within Vortex, but I've reproduced it with just LOOT as I'm pretty sure this is something on LOOT's end. 

Windows 10 Pro
OS Build 19042.1052

I have loot and skyrim installed to D Drive

`LOOTDebugLog.txt`:
```
[21:09:50.718238] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[21:09:50.946921] [warning]: No masterlist present at C:\Users\Ryan\AppData\Local\LOOT\Skyrim VR\masterlist.yaml
[21:09:50.967472] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 2: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[21:09:54.009622] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
[21:09:54.010182] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4403: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:4403:9216)
```

**Comment by TheButlah** [comment]
I have confirmed that I can clone via https the skyrimse.git repo manually via command line, and that if I do that and put it in my %localappdata%/LOOT/Skyrim VR/ folder, things work. But that doesn't solve the issue for vortex, and isn't a long term solution for LOOT either.

**Comment by sibir-ine** [comment]
@TheButlah Can you please provide a [full debug log](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html)?

**Comment by Ortham** [comment]
LOOT's masterlist update never explicitly tries to create a remote, it assumes one called `origin` already exists, so it's not clear why this is happening. Hopefully the debug log will provide some clues.

**Comment by NoirAlter** [comment]
I also have the same problem since yesterday. Already made an exception for loot on windows defender and my firewall. I have also tried uninstalling and reinstalling loot. I have also tried to delete the skyrim folder in the LOOT folder in the Appdata.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/6643688/LOOTDebugLog.txt)

**Comment by sibir-ine** [comment]
@NoirAlter Please enable debug logging & provide a full debug log.

![image](https://user-images.githubusercontent.com/69141501/121803420-57c73b00-cbf6-11eb-84c3-33534ad9da2c.png)

**Comment by NoirAlter** [comment]
Here you go sir

[LOOTDebugLog.txt](https://github.com/loot/loot/files/6643725/LOOTDebugLog.txt)

**Comment by pStyl3** [comment]
@Ortham 
```
[18:45:44.420639] [debug]: Setting the current game to that with folder: Skyrim
[18:45:44.420906] [debug]: New game is: TES V: Skyrim
[18:45:44.421176] [info]: Getting LOOT's detected games.
[18:45:46.075072] [debug]: Updating and parsing masterlist.
[18:45:46.077230] [debug]: Setting up checkout options using branch v0.15 and filename masterlist.yaml.
[18:45:46.077442] [trace]: Checking for Git repository at: C:\Users\Nyor\AppData\Local\LOOT\Skyrim
[18:45:46.125304] [info]: Repository doesn't exist, cloning the remote repository at "https://github.com/loot/skyrim.git".
[18:45:46.126367] [trace]: Target repo path not empty, cloning into temporary directory.
[18:46:08.154366] [debug]: Parsing metadata list(s).
[18:46:08.187354] [error]: Exception while executing query: Git operation failed. Details: -1; failed to send request: The operation timed out
: libgit2 error
[18:46:08.204115] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4403: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:4403:9216)
[18:46:08.225437] [info]: Chromium console message from http://loot/ui/index.html at line 0: Autofocus processing was blocked because a document already has a focused element.
[18:46:16.386218] [info]: Opening LOOT's local appdata folder.
```

**Comment by TheButlah** [comment]
Here is my full debug log, with all the stuff from startup included:
[LOOTDebugLog.txt](https://github.com/loot/loot/files/6644398/LOOTDebugLog.txt)

Here is the debug log, after clearing out everything except when I push the "update masterlist" button:

```
[14:02:49.339247] [debug]: Updating and parsing masterlist.
[14:02:49.340855] [debug]: Setting up checkout options using branch v0.15 and filename masterlist.yaml.
[14:02:49.340950] [trace]: Checking for Git repository at: C:\Users\Ryan\AppData\Local\LOOT\Skyrim VR
[14:02:49.341113] [info]: Repository doesn't exist, cloning the remote repository at "https://github.com/loot/skyrimse.git".
[14:02:49.350848] [debug]: Parsing metadata list(s).
[14:02:49.351130] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
[14:02:49.352087] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4403: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:4403:9216)
[14:02:49.356739] [info]: Chromium console message from http://loot/ui/index.html at line 0: Autofocus processing was blocked because a document already has a focused element.
```

**Comment by Ortham** [comment]
@NoirAlter: Your issue looks like a connectivity issue, I don't think there's anything we can do about it on LOOT's end.

@TheButlah: The log says a git repo doesn't exist at `C:\Users\Ryan\AppData\Local\LOOT\Skyrim VR`: can you double-check if there is a directory at `C:\Users\Ryan\AppData\Local\LOOT\Skyrim VR\.git` or not? The .git folder may be hidden.

**Comment by TheButlah** [comment]
The `Skyrim VR` folder exists, but it is entirely empty. No `.git` folder, hidden or otherwise.

**Comment by TheButlah** [comment]
Any fix for this?

**Comment by Ortham** [comment]
No, sorry, I still don't know how it's going wrong.

**Comment by TheButlah** [comment]
This was solved when I realized that somehow (I don't believe I did this), my global git config was set to have github.com/loot/skyrimse as origin's url. It was even overriding the urls of other projects. So presumably this is what was interfering with LOOT's ability to fetch the masterlist.

How the origin was set in a global manner, and what triggered that setting, remains a mystery to me.

**Comment by Ortham** [comment]
Masterlist update does involve setting the URL for the `origin` remote, but it only acts on the relevant masterlist repository and involves a single `libgit2` API call that I'm pretty sure can't be misused to write to global config...

**Comment by sibir-ine** [comment]
@Ortham Is this something that should/can be investigated further, or can the issue be closed since it was solved for the user?

**Comment by Ortham** [comment]
I think this can be closed, I investigated and didn't find anything that might have caused that global config to be set.
