### ISSUE TITLE
Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error

### ISSUE THREAD

**Issue by Trelleon75** [loot/loot#1685]
Alright so uh, have modded before but still practically new to the whole thing. Game crashes more often than usual, decided it's time to wipe everything. I deleted all the mods via NMM, deleted loot and it's AppData/Local files. deleted all of the save files, and finally, deleted the game entirely. As in through steam, and then manually deleting the folder containing leftover mod files in the steamapps/common/Skyrim Special Edition

After restarting, I downloaded skyrim, downloaded loot, and then launch the game into the main menu. I close the game, and I run loot with no mods yet. It already looks wrong. The general information showns N/A : No masterlist present on both prelude and the original.

Masterlist Revision | N/A: No masterlist present
Masterlist Date | N/A: No masterlist present
Masterlist Prelude Revision | N/A: No masterlist prelude present
Masterlist Prelude Date | N/A: No masterlist prelude present

I then clicked the update masterlist button, and to no suprise, an error message almost immediately. The debug shows this.

```
[22:13:09.191007] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[22:13:09.681656] [warning]: No masterlist prelude present at C:\Users\ASUS\AppData\Local\LOOT\prelude\prelude.yaml
[22:13:09.759395] [warning]: No masterlist present at C:\Users\ASUS\AppData\Local\LOOT\Skyrim Special Edition\masterlist.yaml
[22:13:09.793329] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 2: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[22:13:11.504420] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
[22:13:11.505361] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4413: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
   at onFailure (http://loot/ui/app.bundle.js:4413:9231)
```

Might gives a lot of information to some people. The only thing I can see is that I'm missing something, though I have no idea what might have caused that.
Anyone able to help please?

**Comment by Ortham** [comment]
Try deleting `%LOCALAPPDATA%\LOOT\prelude\.git` and `%LOCAPAPPDATA%\LOOT\Skyrim Special Edition\.git` if they exist (they may be hidden by default).

**Comment by Trelleon75** [comment]
Both the prelude and Skyrim Special Edition folder is actually empty, although I can delete the folder itself

**Comment by Trelleon75** [comment]
Deleted the folder and then loot made a new one, but it's still empty

**Comment by sibir-ine** [comment]
Are you still experiencing a Git error after deleting those two folders? If so, try the other tips in [this Q/A](https://loot.github.io/docs/help/LOOT-FAQs.html#git-errors).

**Comment by Trelleon75** [comment]
Okay, first of all thank you for the help by directing me to the Q/A. I think what I did is installing the prelude and masterlist  manually? It did remove the second and third warning from the debug log, but instead it is replaced with a new one

[16:44:24.459537] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[16:44:24.891452] [warning]: Not a Git repository: C:\Users\ASUS\AppData\Local\LOOT\prelude
[16:44:25.604935] [warning]: Not a Git repository: C:\Users\ASUS\AppData\Local\LOOT\Skyrim Special Edition
[16:44:28.205575] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 2: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[16:44:48.072600] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
[16:44:48.074005] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4413: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:4413:9231)

The git operation error still happens so I still cant't update my masterlist nor sort my plugins. Is there anything else I can do?

**Comment by Ortham** [comment]
That origin already exists error was also reported in #1542, see [this comment](https://github.com/loot/loot/issues/1542#issuecomment-888083153) about it happening because of global Git config, maybe it's the same for you?

**Comment by Trelleon75** [comment]
I...I'm sorry but I have no idea what the comment is saying at all.  Where can I find the global git config and what is an origin's url? I could try searching for it myself but I will be very thankful if any experts here can provide some kind of explanation

**Comment by Ortham** [comment]
The global git config is in a file at `%USERPROFILE%\.gitconfig`, do you have that file? I'm guessing you won't, so your issue might not have the same cause as that other comment...

**Comment by Trelleon75** [comment]
Funny thing is, there actually is that file. I opened it using a notepad and this is what's inside

[remote "origin"]
	url = https://github.com/loot/skyrimse.git

And it looks like my case is somewhat similar to the comment you mentioned. However the comment doesn't really gives any solution, rather only mentions what seems to be the problem. So after finding this, what am I supposed to do exactly?

**Comment by Trelleon75** [comment]
Uh so, I just deleted it, and apparently everything is fixed. Somewhat anticlimactic but hey I'll take it. Thank you so much for the help you two.

**Comment by Trelleon75** [comment]
Oh and for the record, just like the previous guy I also have no idea what caused that setting.
