### ISSUE TITLE
missing masterslist

### ISSUE THREAD

**Issue by TheLycanMaster** [loot/loot#1702]
new to modding. this could be my fault do not know. but I am missing my masterlist.yaml and I can't update my masterlist on loot or sort plugins on loot for skyrim special edition.  i ma using vortex mod manager at the moment for my main modding program. 

<details>

<summary>lootdebuglog text document</summary>

```
[13:43:29.633754] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[13:43:30.161639] [warning]: No masterlist prelude present at C:\Users\Chad D Warren\AppData\Local\LOOT\prelude\prelude.yaml
[13:43:30.285430] [warning]: No masterlist present at C:\Users\Chad D Warren\AppData\Local\LOOT\Morrowind\masterlist.yaml
[13:43:30.322822] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 2: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[13:43:46.116215] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
[13:43:46.117305] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4413: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:4413:9231)
[13:44:08.230095] [warning]: No masterlist present at C:\Users\Chad D Warren\AppData\Local\LOOT\Skyrim Special Edition\masterlist.yaml
[13:44:08.263468] [warning]: "BVLT - High Elf.esp" has a header version of 0.94, which is less than the game's minimum supported header version of 1.7.
[13:44:08.310102] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 2: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[13:44:12.266426] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
[13:44:12.275184] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4413: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:4413:9231)
[13:44:33.193797] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
[13:44:33.194588] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4413: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:4413:9231)
[13:44:56.611387] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
[13:44:56.619580] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4413: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:4413:9231)
[13:45:47.301514] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
[13:45:47.310749] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4413: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:4413:9231)
[13:46:37.040019] [warning]: No masterlist present at C:\Users\Chad D Warren\AppData\Local\LOOT\Skyrim Special Edition\masterlist.yaml
[13:46:37.072181] [warning]: "BVLT - High Elf.esp" has a header version of 0.94, which is less than the game's minimum supported header version of 1.7.
[13:46:37.115485] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 2: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[13:47:09.014741] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
[13:47:09.015682] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4413: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:4413:9231)
[13:49:44.503838] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
[13:49:44.506328] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4413: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:4413:9231)
[13:49:46.646307] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
[13:49:46.647034] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4413: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:4413:9231)
[13:50:52.052139] [error]: Exception while executing query: Git operation failed. Details: -4; remote 'origin' already exists: libgit2 error
[13:50:52.062634] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 4413: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:4413:9231)
```

</details>

i hope this is how i ask a question new to github

**Comment by Ortham** [comment]
Try deleting your `C:\Users\Chad D Warren\AppData\Local\LOOT\Skyrim Special Edition\` folder.

**Comment by TheLycanMaster** [comment]
i did

**Comment by sibir-ine** [comment]
Try deleting the `C:\Users\Chad D Warren\AppData\Local\LOOT\prelude\` folder too.

If that doesn't work, it looks like it's related to #1542. See if there's a `.gitconfig` file in `C:\Users\Chad D Warren\`. If so, open it with a text editor & see if there's a line like `url = https://github.com/loot/skyrimse.git`. If so, trying removing it (or deleting `.gitconfig` if you don't even use Git).

**Comment by sibir-ine** [comment]
@TheLycanMaster, since v0.18.0 has been released & drops the Git-based update system, this issue can be resolved by updating to the latest version.
