### ISSUE TITLE
N/A masterlist??

### ISSUE THREAD

**Issue by AdministrativeSmile** [loot/loot#898]
I can't sort the plugins here is my log.

[20:53:58.511603] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[20:53:58.541603] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[20:53:59.110603] [warning]: No masterlist present at C:\Users\KIBA\AppData\Local\LOOT\Skyrim\masterlist.yaml
[20:54:03.362603] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[20:54:03.362603] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)
[20:54:08.560603] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[20:54:08.560603] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)
[20:54:12.956603] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[20:54:12.956603] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)
![capture](https://user-images.githubusercontent.com/36871848/36708355-378c0f18-1b38-11e8-872e-f599892deac0.JPG)

**Comment by warmfrost85** [comment]
You're probably using win7. This is a duplicate of #882  Refer to it for a solution.

**Comment by WrinklyNinja** [comment]
That's loot/loot#882, see the fix that's given in that issue thread, the release notes, readme and FAQs.
