### ISSUE TITLE
Error= "Oh No Somthing Went Wrong"

### ISSUE THREAD

**Issue by SomeYank** [loot/loot#899]
geting this error whn trying to sort mods:

lootdebuglog.txt shows this:

[09:33:16.325524] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.

[09:33:16.403524] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[09:33:17.577561] [warning]: No masterlist present at C:\Users\Chris\AppData\Local\LOOT\Fallout4\masterlist.yaml

[09:33:24.729767] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error

[09:33:24.729767] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)

[09:34:38.863933] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error

[09:34:38.864933] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information. at onFailure (http://loot/ui/js/query.js:43:16)

total noob here peeps, so sorry if i posted this in wrong in any way.

**Comment by William-Imm** [comment]
This is a duplicate of #882, refer to it or the FAQ for a solution.
