### ISSUE TITLE
Pile of errors

### ISSUE THREAD

**Issue by MaulMachine** [loot/loot#904]
Hello,

I was running the new release of 0.12.4, and as soon as I tried to sort plugins, it spat out an error and stopped.  I manually uninstalled and deleted all LOOT files including AppData, downloaded the newest release, and tried again, and it dropped this in an error:

[22:54:21.282175] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[22:54:21.336179] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[22:54:22.249231] [warning]: No masterlist present at C:\Users\MaulMachine\AppData\Local\LOOT\Skyrim\masterlist.yaml
[22:54:24.924384] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[22:54:24.924384] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)
[22:54:29.308635] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[22:54:29.309635] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)

EDIT: IT seems another thread on this already exists.  I'll try the Microsoft "Easy Fix".

EDIT: fb    And done.  Sorry about the superfluous thread.

**Comment by WrinklyNinja** [comment]
That's loot/loot#882, see the fix that's given in that issue thread, the release notes, readme and FAQs.
