### ISSUE TITLE
Blocking load of resource, no masterlist present, exception while executing query (libgit2 error)

### ISSUE THREAD

**Issue by CrazyOatmeal** [loot/loot#933]
Blocking Load of Resource error at fonts.googleapis, no masterlist present, same old shit. Searched the other threads, allowed through firewall, installed TLS 1.1 and 1.2 update, updated and reinstalled LOOT, everything. 

_[23:07:30.190413] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[23:07:30.276418] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[23:07:31.571492] [warning]: No masterlist present at C:\Users\Adam\AppData\Local\LOOT\Skyrim\masterlist.yaml
[23:07:42.833136] [error]: Exception while executing query: Git operation failed. Details: -4; 'C:\Users\Adam\AppData\Local\LOOT\Skyrim' exists and is not an empty directory: libgit2 error
[23:07:42.856137] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:140358)
[23:07:55.973888] [error]: Exception while executing query: Git operation failed. Details: -4; 'C:\Users\Adam\AppData\Local\LOOT\Skyrim' exists and is not an empty directory: libgit2 error
[23:07:55.974888] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:140358)_

**Comment by CptMcSplody** [comment]
C:\Users\Adam\AppData\Local\LOOT\ 
Make a backup of the files inside and the delete the contents of C:\Users\Adam\AppData\Local\LOOT\

Then run loot again.

**Comment by CrazyOatmeal** [comment]
Solved. Thanks bud. Don't know why I didn't try that already.
