### ISSUE TITLE
No plugins Mod Organizer

### ISSUE THREAD

**Issue by SPQRdaVinci** [loot/loot#950]
error message: Failed to sort plugins. Details: see general messages for details.

CEFDebugLog: [0523/134933:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak

LOOTDebugLog: 
[14:01:07.183977] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[14:01:07.274619] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[14:01:09.587807] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Failed to sort plugins. Details: see general messages for details.
    at Y.e.then.then.then.e (http://loot/ui/app.bundle.js:1:157976)
    at <anonymous>

**Comment by Freso** [comment]
Do you get the same error when running outside of Mod Organizer?

**Comment by SPQRdaVinci** [comment]
It works outside MO
i reinstalled MO and loot and it still wont work

**Comment by SPQRdaVinci** [comment]
[13:06:57.298099] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[13:06:57.403260] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[13:07:01.400284] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Failed to sort plugins. Details: see general messages for details.
    at Y.e.then.then.then.e (http://loot/ui/app.bundle.js:1:157976)
    at <anonymous>
[13:07:22.097984] [trace]: Updating existing games and adding new games.
[13:07:22.098044] [trace]: Checking if game "TES IV: Oblivion" is installed.
[13:07:22.098206] [trace]: Getting string for registry key, subkey and value: HKEY_LOCAL_MACHINE, Software\Bethesda Softworks\Oblivion, Installed Path
[13:07:22.098274] [info]: Failed to get string value.
[13:07:22.098304] [trace]: Checking if game "TES V: Skyrim Special Edition" is installed.
[13:07:22.098384] [trace]: Getting string for registry key, subkey and value: HKEY_LOCAL_MACHINE, Software\Bethesda Softworks\Skyrim Special Edition, Installed Path
[13:07:22.098432] [info]: Failed to get string value.
[13:07:22.098455] [trace]: Checking if game "Fallout 3" is installed.
[13:07:22.098527] [trace]: Getting string for registry key, subkey and value: HKEY_LOCAL_MACHINE, Software\Bethesda Softworks\Fallout3, Installed Path
[13:07:22.098573] [info]: Failed to get string value.
[13:07:22.098599] [trace]: Checking if game "Fallout: New Vegas" is installed.
[13:07:22.098668] [trace]: Getting string for registry key, subkey and value: HKEY_LOCAL_MACHINE, Software\Bethesda Softworks\FalloutNV, Installed Path
[13:07:22.098720] [info]: Failed to get string value.
[13:07:22.098747] [trace]: Checking if game "Fallout 4 VR" is installed.
[13:07:22.098814] [trace]: Getting string for registry key, subkey and value: HKEY_LOCAL_MACHINE, Software\Bethesda Softworks\Fallout 4 VR, Installed Path
[13:07:22.098858] [info]: Failed to get string value.
[13:07:22.098879] [trace]: Checking if game "Nehrim - At Fate's Edge" is installed.
[13:07:22.098969] [trace]: Getting string for registry key, subkey and value: HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\Nehrim - At Fate's Edge_is1, InstallLocation
[13:07:22.099021] [info]: Failed to get string value.
[13:07:22.099040] [trace]: Removing deleted games.
[13:07:22.099054] [info]: Initialising filesystem-related data for game: TES V: Skyrim
[13:07:22.099202] [info]: Getting LOOT's detected games.
[13:07:23.124163] [debug]: Updating and parsing masterlist.
[13:07:23.126213] [debug]: Setting up checkout options.
[13:07:23.126246] [trace]: Attempting to open the Git repository at: C:\Users\Calvin Choi\AppData\Local\LOOT\Skyrim
[13:07:23.126643] [info]: Existing repository found, attempting to open it.
[13:07:23.127675] [info]: Using remote URL: https://github.com/loot/skyrim.git
[13:07:23.127707] [trace]: Fetching updates from remote.
[13:07:25.644902] [trace]: Received 0 of 0 objects in 0 bytes.
[13:07:25.646260] [trace]: Checking HEAD and remote branch's mergeability.
[13:07:25.647271] [trace]: Local branch is up-to-date with remote branch. Checking to see if local and remote branch heads are equal.
[13:07:25.647293] [trace]: Local and remote branch heads are equal.
[13:07:25.647637] [trace]: Existing repository found, attempting to open it.
[13:07:25.648616] [trace]: Getting the tree for the HEAD revision.
[13:07:25.649843] [trace]: Performing git diff.
[13:07:25.656201] [trace]: Iterating over git diff deltas.
[13:07:25.656635] [trace]: Checking diff for: .gitattributes
[13:07:25.657056] [trace]: Checking diff for: .gitignore
[13:07:25.657393] [trace]: Checking diff for: .travis.yml
[13:07:25.657725] [trace]: Checking diff for: CONTRIBUTING.md
[13:07:25.658420] [trace]: Checking diff for: LICENSE
[13:07:25.658775] [trace]: Checking diff for: README.md
[13:07:25.658800] [trace]: Recursively setting write permission on directory: C:/Users/Calvin Choi/AppData/Local/LOOT/Skyrim/.git/
[13:07:25.661243] [info]: Local branch and masterlist file are already up to date.
[13:07:25.661279] [trace]: Recursively setting write permission on directory: C:/Users/Calvin Choi/AppData/Local/LOOT/Skyrim/.git/
[13:07:25.665048] [info]: Beginning sorting operation.
[13:07:25.665090] [trace]: Sending progress update: Sorting load order...
[13:07:25.665121] [trace]: Scanning for plugins in D:\Skyrim - Legendary Edition\Data
[13:07:25.665416] [info]: Loading 0 plugins using 1 threads, with up to 0 plugins per thread.
[13:07:25.665447] [debug]: Loading the current load order state.
[13:07:25.673311] [trace]: Starting plugin loading.
[13:07:25.673809] [info]: Merging masterlist, userlist into plugin list, evaluating conditions and checking for install validity.
[13:07:25.673885] [trace]: Evaluating condition: file("SKSE/Plugins/SKSE_Elys_Uncapper.dll") and not file("../skse_loader.exe")
[13:07:25.673950] [trace]: Checking to see if the file "SKSE/Plugins/SKSE_Elys_Uncapper.dll" exists.
[13:07:25.673974] [trace]: Checking to see if the path "SKSE/Plugins/SKSE_Elys_Uncapper.dll" is safe.
[13:07:25.674158] [trace]: File check result: false
[13:07:25.674182] [trace]: Checking to see if the file "../skse_loader.exe" exists.
[13:07:25.674198] [trace]: Checking to see if the path "../skse_loader.exe" is safe.
[13:07:25.674348] [trace]: File check result: true
[13:07:25.674380] [trace]: Evaluating condition: file("../skse_loader.exe") and version("../skse_loader.exe", "0.1.7.3", <)
[13:07:25.674419] [trace]: Checking to see if the file "../skse_loader.exe" exists.
[13:07:25.674436] [trace]: Checking to see if the path "../skse_loader.exe" is safe.
[13:07:25.674564] [trace]: File check result: true
[13:07:25.674592] [trace]: Checking the version of the file "../skse_loader.exe".
[13:07:25.674610] [trace]: Checking to see if the path "../skse_loader.exe" is safe.
[13:07:25.674802] [trace]: Checking to see if "../skse_loader.exe" is a valid plugin.
[13:07:25.675419] [trace]: Version extracted: 0.1.7.3
[13:07:25.675469] [trace]: Version check result: false
[13:07:25.675511] [trace]: Evaluating condition: not version("../skse_loader.exe", "0.1.7.3", <)
[13:07:25.675561] [trace]: Checking the version of the file "../skse_loader.exe".
[13:07:25.675580] [trace]: Checking to see if the path "../skse_loader.exe" is safe.
[13:07:25.675820] [trace]: Checking to see if "../skse_loader.exe" is a valid plugin.
[13:07:25.676365] [trace]: Version extracted: 0.1.7.3
[13:07:25.676407] [trace]: Version check result: false
[13:07:25.676441] [trace]: Evaluating condition: file("ASIS(-Dependency)?\.esp") or file("Automatic (Spells|Variations|Variants)\.esp")
[13:07:25.676489] [trace]: Checking to see if the file "ASIS(-Dependency)?\.esp" exists.
[13:07:25.676520] [trace]: Checking to see if the path "" is safe.
[13:07:25.676988] [trace]: File check result: false
[13:07:25.677020] [trace]: Checking to see if the file "Automatic (Spells|Variations|Variants)\.esp" exists.
[13:07:25.677048] [trace]: Checking to see if the path "" is safe.
[13:07:25.677421] [trace]: File check result: false
[13:07:25.677468] [trace]: Evaluating condition: file("tools/GenerateFNIS_for_Users/GenerateFNISforUsers.exe")
[13:07:25.677517] [trace]: Checking to see if the file "tools/GenerateFNIS_for_Users/GenerateFNISforUsers.exe" exists.
[13:07:25.677539] [trace]: Checking to see if the path "tools/GenerateFNIS_for_Users/GenerateFNISforUsers.exe" is safe.
[13:07:25.677748] [trace]: File check result: true
[13:07:25.680441] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Failed to sort plugins. Details: see general messages for details.
    at Y.e.then.then.then.e (http://loot/ui/app.bundle.js:1:157976)
    at <anonymous>
[13:07:32.596681] [info]: Opening LOOT's local appdata folder.

**Comment by WrinklyNinja** [comment]
> It works outside MO
> i reinstalled MO and loot and it still wont work

Sorry, but running LOOT through Mod Organiser is unsupported, as most issues reported by Mod Organiser users are caused by Mod Organiser, which I can't do anything about.
