### ISSUE TITLE
Loot Cant detect Plugins For Fallout 4

### ISSUE THREAD

**Issue by Arvezia** [loot/loot#951]
So this is the first time i use LOOT,when i open it, LOOT just detect my base game and DLC .esm and not detect any of my mod plugin(its usually have .esp extension)
i use NMM for modding, so i try to move all of my mod to base game install path and reinstall it, but LOOT still dont detect all of my mod

any solution?

**Comment by Arvezia** [comment]
it detect the game, it just wont detect all of my mods

**Comment by Arvezia** [comment]
i try to delete fallout 4 folder on /appdata/local/LOOT, now i try to sort plugins to update and this show up
[22:33:53.152763] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[22:33:53.366234] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[22:36:24.682041] [error]: libloadorder failed to set the load order. Details: Access is denied. (os error 5)
[22:36:24.723992] [error]: Exception while executing query: libloadorder failed to set the load order. Details: Access is denied. (os error 5): Libloadorder error
[22:36:24.800343] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! This is usually because your plugins.txt is set to be read-only. If it is, unset it and try again. If it isn't, you can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:140358)
[22:36:39.064791] [error]: libloadorder failed to set the load order. Details: Access is denied. (os error 5)
[22:36:39.064997] [error]: Exception while executing query: libloadorder failed to set the load order. Details: Access is denied. (os error 5): Libloadorder error
[22:36:39.066100] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! This is usually because your plugins.txt is set to be read-only. If it is, unset it and try again. If it isn't, you can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:140358)

**Comment by Arvezia** [comment]
i check the plugin.txt and its not read only
for some reason i could sort plugin now, but my mods still not showing

**Comment by Arvezia** [comment]
[18:13:59.380212] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[18:14:00.925538] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic

**Comment by WrinklyNinja** [comment]
That's not a debug log with debug logging enabled, it should contain a lot more than that.

**Comment by Arvezia** [comment]
[17:41:18.055748] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[17:41:19.731690] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[17:41:44.832948] [trace]: Updating existing games and adding new games.
[17:41:44.833166] [trace]: Checking if game "TES IV: Oblivion" is installed.
[17:41:44.839138] [trace]: Getting string for registry key, subkey and value: HKEY_LOCAL_MACHINE, Software\Bethesda Softworks\Oblivion, Installed Path
[17:41:44.839414] [info]: Failed to get string value.
[17:41:44.839497] [trace]: Checking if game "TES V: Skyrim" is installed.
[17:41:44.839682] [trace]: Getting string for registry key, subkey and value: HKEY_LOCAL_MACHINE, Software\Bethesda Softworks\Skyrim, Installed Path
[17:41:44.839816] [info]: Failed to get string value.
[17:41:44.839864] [trace]: Checking if game "TES V: Skyrim Special Edition" is installed.
[17:41:44.839985] [trace]: Getting string for registry key, subkey and value: HKEY_LOCAL_MACHINE, Software\Bethesda Softworks\Skyrim Special Edition, Installed Path
[17:41:44.840100] [info]: Failed to get string value.
[17:41:44.840186] [trace]: Checking if game "Fallout 4 VR" is installed.
[17:41:44.840314] [trace]: Getting string for registry key, subkey and value: HKEY_LOCAL_MACHINE, Software\Bethesda Softworks\Fallout 4 VR, Installed Path
[17:41:44.840434] [info]: Failed to get string value.
[17:41:44.840480] [trace]: Checking if game "Nehrim - At Fate's Edge" is installed.
[17:41:44.840605] [trace]: Getting string for registry key, subkey and value: HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\Nehrim - At Fate's Edge_is1, InstallLocation
[17:41:44.840723] [info]: Failed to get string value.
[17:41:44.840761] [trace]: Removing deleted games.
[17:41:44.840795] [info]: Initialising filesystem-related data for game: Fallout 4
[17:41:44.841079] [info]: Getting LOOT's detected games.
[17:41:49.249405] [debug]: Updating and parsing masterlist.
[17:41:49.252188] [debug]: Setting up checkout options.
[17:41:49.252269] [trace]: Attempting to open the Git repository at: C:\Users\Arve Rezzle\AppData\Local\LOOT\Fallout4
[17:41:49.253047] [info]: Existing repository found, attempting to open it.
[17:41:49.254956] [info]: Using remote URL: https://github.com/loot/fallout4.git
[17:41:49.255068] [trace]: Fetching updates from remote.
[17:41:50.712257] [trace]: Received 0 of 0 objects in 0 bytes.
[17:41:50.714377] [trace]: Checking HEAD and remote branch's mergeability.
[17:41:50.716309] [trace]: Local branch is up-to-date with remote branch. Checking to see if local and remote branch heads are equal.
[17:41:50.716363] [trace]: Local and remote branch heads are equal.
[17:41:50.717041] [trace]: Existing repository found, attempting to open it.
[17:41:50.718848] [trace]: Getting the tree for the HEAD revision.
[17:41:50.721747] [trace]: Performing git diff.
[17:41:50.725446] [trace]: Iterating over git diff deltas.
[17:41:50.726190] [trace]: Checking diff for: .gitattributes
[17:41:50.726994] [trace]: Checking diff for: .gitignore
[17:41:50.727741] [trace]: Checking diff for: .travis.yml
[17:41:50.728425] [trace]: Checking diff for: CONTRIBUTING.md
[17:41:50.729208] [trace]: Checking diff for: LICENSE
[17:41:50.729893] [trace]: Checking diff for: README.md
[17:41:50.729963] [trace]: Recursively setting write permission on directory: C:/Users/Arve Rezzle/AppData/Local/LOOT/Fallout4/.git/
[17:41:50.734526] [info]: Local branch and masterlist file are already up to date.
[17:41:50.734614] [trace]: Recursively setting write permission on directory: C:/Users/Arve Rezzle/AppData/Local/LOOT/Fallout4/.git/

**Comment by WrinklyNinja** [comment]
There's still a lot missing there. Please just start LOOT, close it once it's initialised, then upload your LOOTDebugLog.txt (not copy/paste its contents).

**Comment by Arvezia** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2043190/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Well, LOOT isn't even seeing any mod files in your Data folder, can you actually see them in Windows' file explorer? I don't have FO4 installed, but I just tried installing a Skyrim SE mod with NMM and it appeared in the Data folder and LOOT was able to see it.

**Comment by Arvezia** [comment]
![image](https://user-images.githubusercontent.com/39557043/40634330-8fd4b778-631e-11e8-95b8-5953a3f6109a.png)
Yes i can, its right there but loot cant detect it

**Comment by Arvezia** [comment]
yes this is the right one

**Comment by WrinklyNinja** [comment]
If it's the right one, then you need to configure LOOT to use it, I guess your Registry settings are inaccurate so LOOT picked the wrong one from them.

**Comment by Arvezia** [comment]
err...how do i configure my registry? i only configure the game path on LOOT

**Comment by WrinklyNinja** [comment]
The game launcher sets the appropriate registry key when you run it, though I don't know if that happens if the key already exists. If you've got the game path configured in LOOT though, it'll use that and skip checking the registry.

**Comment by Ghostwalker71** [comment]
@Arvezia   You should download and run a registry cleaner to remove all of the invalid registry entries. Here http://www.ccleaner.com/ccleaner is a good free option. There are many others as well. After cleaning the invalid registries then run the game launcher to make sure the correct registry entry is made and then try loot again.
