### ISSUE TITLE
Loot seems to be having trouble sorting my plugins

### ISSUE THREAD

**Issue by Enderman51** [loot/loot#955]
The following is a copy and paste of my LOOTDebugLog.txt

[18:08:19.462710] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[18:08:19.981022] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[18:08:35.269560] [warning]: No masterlist present at C:\Users\Heaven\AppData\Local\LOOT\Fallout4\masterlist.yaml
[18:10:43.689246] [error]: Exception while executing query: boost::filesystem::status: Access is denied: "C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\F4SE/Plugins/achievements.dll"
[18:10:43.743170] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:140358)
[18:15:10.706122] [error]: Exception while executing query: boost::filesystem::status: Access is denied: "C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\F4SE/Plugins/achievements.dll"
[18:15:10.706709] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:140358)

**Comment by WrinklyNinja** [comment]
```
[18:10:43.689246] [error]: Exception while executing query: boost::filesystem::status: Access is denied: "C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\F4SE/Plugins/achievements.dll"
```

Somehow LOOT doesn't even have read access to this file, does it exist? Does sorting work if you run LOOT as an admin?

**Comment by Enderman51** [comment]
No it does not work when under admin. here is the LOOTDebugLog.txt from when i run it under admin.

[06:37:21.864916] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[06:37:22.366592] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[06:37:23.754199] [error]: Exception while executing query: boost::filesystem::status: Access is denied: "C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\F4SE/Plugins/achievements.dll"
[06:37:28.395103] [error]: Exception while executing query: boost::filesystem::status: Access is denied: "C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\F4SE/Plugins/achievements.dll"
[06:37:28.396207] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:140358)

**Comment by WrinklyNinja** [comment]
Exactly the same issue...

- Does the file exist?
- Is it a normal file or a symlink/hardlink?
- Are you able to access it, move it around and rename it? (Put it back in its original place with its original name once you've tested.)

**Comment by Enderman51** [comment]
its a f4se is a folder with another folder called plugins. when clicking on this plug in folder a Location not available error pops up. when trying to move the whole f4se folder with the plugin folder inside i am prompted that i need admin permission to do so. but i am the admin on my computer

**Comment by Enderman51** [comment]
ok so, i restarted my computer made sure steam did not open and i didn't open task manager upon restart like i usually do , and went back to the f4se file in my data folder this time i was able to move it to my desktop and delete it, that seems to fix the problem. your program was able to do its task both with and with out running under admin.  thank you for all your hard work

**Comment by WrinklyNinja** [comment]
For future reference, this can sometimes also happen if NTFS permissions get corrupted, and restarting doesn't always help. In that case, my usual solution is to use [Unlocker](http://www.emptyloop.com/unlocker/) to delete the file/folder.

**Comment by Enderman51** [comment]
ok thanks for the advice will def look into it and use it next time
