### ISSUE TITLE
Access denied when renaming during masterlist update

### ISSUE THREAD

**Issue by Darkcyde13** [loot/loot#965]
(Pasted from Issue #964 )

I've been having a similar problem. At first LOOT said the Masterlist was missing and my log was as follows:-
```
[14:36:17.315583] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[14:36:17.379364] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[14:36:18.825690] [warning]: Not a Git repository: C:\Users\Jason\AppData\Local\LOOT\Fallout4
[14:36:24.790794] [error]: Exception while executing query: boost::filesystem::rename: Access is denied: "E:\WinTemp\LOOT-Fallout4-d7b6-a51e-e6a2-68b5\.git", "C:\Users\Jason\AppData\Local\LOOT\Fallout4\.git"
[14:36:24.791576] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)
[14:36:28.873915] [error]: Exception while executing query: boost::filesystem::rename: Access is denied: "E:\WinTemp\LOOT-Fallout4-fb92-fbe9-5616-d79e\.git", "C:\Users\Jason\AppData\Local\LOOT\Fallout4\.git"
[14:36:28.874358] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)

```
This was before I read that I needed the debug turned on in settings. The Fallout4 folders on both C: and E: are full access, not read only.  It looks like the error says it's trying to open a file with no filename? '\.git'?

Anyway, after enabling the debug option in settings, LOOT says the Masterlist is 'Unkown, Git repository missing'. and I get the log as attached.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2066006/LOOTDebugLog.txt)

I've tried Ghostwalker71's suggestion of opening NMM (version 65.2) and closing without doing anything, and now LOOT refuses to run at all.

EDIT:  Since commenting on the original open issue, I've tried the new version of LOOT with the same results, as follows.

I've enabled debug logging, and LOOT is reporting the masterlist as 'N/A: No masterlist present'.  I run Update Masterlist and get the error, I try to sort and get the error again. Log attached.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2066021/LOOTDebugLog.txt)

Again, I've tried Ghostwalker71's suggestion of loading NMM first, doing nothing and closing it, but I still get the same errors. Although this time, it is running now.

I've also noticed that LOOT is leaving temp folders behind for every execution, at about 500KB a time.  This is quickly adding up with multiple executions.

**Comment by WrinklyNinja** [comment]
And there I was thinking I'd finally fixed this class of issue...

```
[14:39:03.385890] [debug]: Updating and parsing masterlist.
[14:39:03.389156] [debug]: Setting up checkout options.
[14:39:03.389178] [debug]: Using remote URL https://github.com/loot/fallout4.git and branch v0.13
[14:39:03.389193] [debug]: Setting up checkout options uUsing branch v0.13 and filename masterlist.yaml.
[14:39:03.389209] [trace]: Checking for Git repository at: C:\Users\Jason\AppData\Local\LOOT\Fallout4
[14:39:03.389510] [info]: Repository doesn't exist, cloning the remote repository.
[14:39:03.389840] [trace]: Target repo path not empty, cloning into temporary directory.
[14:39:03.947623] [trace]: Target repo path not empty, renaming and moving previous content back in.
[14:39:03.947661] [trace]: Recursively setting write permission on directory: C:\Users\Jason\AppData\Local\LOOT\Fallout4
[14:39:03.947896] [trace]: Recursively setting write permission on directory: E:\WinTemp\LOOT-Fallout4-0233-336d-7aeb-7a3c
[14:39:03.948966] [trace]: Setting write permission for: E:\WinTemp\LOOT-Fallout4-0233-336d-7aeb-7a3c\.git\objects\pack\pack-d15d50286ee6c405f378c7fc2e0744d987830518.idx
[14:39:03.949155] [trace]: Setting write permission for: E:\WinTemp\LOOT-Fallout4-0233-336d-7aeb-7a3c\.git\objects\pack\pack-d15d50286ee6c405f378c7fc2e0744d987830518.pack

...

[14:39:04.064737] [error]: Exception while executing query: boost::filesystem::rename: Access is denied: "E:\WinTemp\LOOT-Fallout4-0233-336d-7aeb-7a3c\.git", "C:\Users\Jason\AppData\Local\LOOT\Fallout4\.git"
[14:39:04.065248] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)
```

Can you check if the files at `E:\WinTemp\LOOT-Fallout4-0233-336d-7aeb-7a3c\.git\objects\pack\pack-d15d50286ee6c405f378c7fc2e0744d987830518.idx` and `E:\WinTemp\LOOT-Fallout4-0233-336d-7aeb-7a3c\.git\objects\pack\pack-d15d50286ee6c405f378c7fc2e0744d987830518.pack` are read-only or not (the .git folder might be hidden)?

Also try running LOOT as admin, see if that changes anything.

**Comment by Darkcyde13** [comment]
Every user or group has access to read/write/modify both those files.  The .git folder is hidden, but I have my PC set to show hidden files and folders.

I had already tried to run LOOT as Admin, but that had no effect.

**Comment by WrinklyNinja** [comment]
Try replacing the `loot_api.dll` in your LOOT install with [this one](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_api-0.13.5-1-g315622b_avoid-undefined-behaviour-win32.7z). You might be falling foul of some undefined behaviour.

**Comment by Darkcyde13** [comment]
Copied and overwritten the install with the ones from your archive. Still getting the errors though.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2066114/LOOTDebugLog.txt)
Also tried again as Admin, still no luck.

I just thought though, did you want me to ONLY use that one API file, or use all of the archive? I did use the whole thing.

I'm not 100% sure what I'm actually doing with LOOT, so I hope I'm not making a noob mistake that's causing this.

**Comment by WrinklyNinja** [comment]
Damn, nothing else jumps out at me... Though if you just take the .git folder and masterlist.yaml from the temporary directory and put them in your `LOOT\Fallout4`, you should be able to update your masterlist in future.

> I just thought though, did you want me to ONLY use that one API file, or use all of the archive? I did use the whole thing.

Only that file, but it doesn't matter, the others won't have any effect.

**Comment by Darkcyde13** [comment]
Thank you, copying those over does fix the errors.  I hope it's not too difficult to find the initial problem though. Good luck, and thanks again! :)

**Comment by CptMcSplody** [comment]
@WrinklyNinja I think I encountered this issue, when switching over to v0.13 from v0.10 without clearing out the appdata folder. That was ages ago though, I may be remember it incorrectly.

**Comment by WrinklyNinja** [comment]
> @WrinklyNinja I think I encountered this issue, when switching over to v0.13 from v0.10 without clearing out the appdata folder. That was ages ago though, I may be remembering it incorrectly.

I've changed the logic since then, in part to try fixing access denied issues.

**Comment by Ortham** [comment]
This issue is probably the same as the one in #1015 that has been fixed, so closing this.
